version: "3.9"

services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: vite-frontend
        ports:
            - "3000:80"
        restart: unless-stopped
