export const GET_POKEMONS_REQUEST = "GET_POKEMONS_REQUEST";
export const GET_POKEMONS_SUCCESS = "GET_POKEMONS_SUCCESS";
export const GET_POKEMONS_FAILED = "GET_POKEMONS_FAILED";

export const GET_POKEMON_REQUEST = "GET_POKEMON_REQUEST";
export const GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS";
export const GET_POKEMON_FAILED = "GET_POKEMON_FAILED";

export const GET_POKEMONS_BY_TYPE_REQUEST = "GET_POKEMONS_BY_TYPE_REQUEST";
export const GET_POKEMONS_BY_TYPE_SUCCESS = "GET_POKEMONS_BY_TYPE_SUCCESS";
export const GET_POKEMONS_BY_TYPE_FAILED = "GET_POKEMONS_BY_TYPE_FAILED";

export const CLEAR_SEARCH = "CLEAR_SEARCH";
